version: '3'
services:
  WS:
    image: nginx
    ports:
      - "20080:80"
    restart: always
    environment:
      TZ : "Asia/Seoul"
    networks:
      network:
    volumes:
      - html:/usr/share/nginx/html
      - nginx:/etc/nginx 

  backend:
    build: .
    ports:
      - "23000:3000"
    restart: always
    volumes:
      - public:/usr/src/app/public
    networks:
      network:
    environment:
      NODE_ENV: production
      TZ : "Asia/Seoul"

  db:
    image: postgres
    restart: always
    networks:
      network:
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: seongcheol
      TZ : "Asia/Seoul"
    ports:
      - "25432:5432" 
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  html:
  nginx:
  db:
  public:

networks:
  network:
